In [34]:
import numpy as np
arr2 = np.array([-9,2,23.2,5])

In [35]:
np.array([-9,7,4,3], dtype='str')

array(['-9', '7', '4', '3'], dtype='<U2')

In [36]:
arr3 = np.array([[2, -1, 8, 3], [2, 5, -1, 2],[2,5,2,6]])

In [37]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [38]:
np.linspace(1,10,10,endpoint=False)


array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [39]:
np.logspace(1,5,base=2,num=10)


array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [40]:
2 ** np.linspace(1,5,10)


array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [41]:
np.zeros([5,4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones([7,6])


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.diag([4,5,8])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 8]])

In [45]:
arr2.shape


(4,)

In [46]:
np.size([1,5,6])


3

In [50]:
arr3.ndim


2

In [49]:
arr2.ndim


1

In [51]:
arr3.shape


(3, 4)

In [52]:
arr3.size

12

In [55]:
arr4 = np.array([-9,7,4,3], dtype='int')
arr4.dtype

dtype('int32')