In [178]:
import numpy as np

In [179]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
arr1[-4:-2]
arr1[5] = 20
arr1

array([ 1,  2,  3,  4,  5, 20,  7,  8,  9])

In [181]:
id(arr1)

2640521021200

In [182]:
arr_change = arr1
id(arr_change)


2640521021200

In [183]:
arr_change = arr1.copy()
arr_change[1:3]=[4,9]
arr_change

array([ 1,  4,  9,  4,  5, 20,  7,  8,  9])

In [184]:
arr1


array([ 1,  2,  3,  4,  5, 20,  7,  8,  9])

In [185]:
data2 = ((8,5,2,62,1),(12,2,62.,2,5),(2,5.61,2,62,1))
arr2 = np.array(data2)
arr2

array([[ 8.  ,  5.  ,  2.  , 62.  ,  1.  ],
       [12.  ,  2.  , 62.  ,  2.  ,  5.  ],
       [ 2.  ,  5.61,  2.  , 62.  ,  1.  ]])

In [186]:
arr2[2]

array([ 2.  ,  5.61,  2.  , 62.  ,  1.  ])

In [187]:
arr2[2, 1]


5.61

In [188]:
arr2[:,2:4]


array([[ 2., 62.],
       [62.,  2.],
       [ 2., 62.]])

In [189]:
arr2[1:,2:4]

array([[62.,  2.],
       [ 2., 62.]])

In [190]:
arr2[1:0][2:4]


array([], shape=(0, 5), dtype=float64)

In [191]:
arr2[arr2>3.5]

array([ 8.  ,  5.  , 62.  , 12.  , 62.  ,  5.  ,  5.61, 62.  ])

In [192]:
arr2[~(arr2>=3.5)]


array([2., 1., 2., 2., 2., 2., 1.])

In [193]:
arr2[(arr2>3.5)&(arr2<10)]



array([8.  , 5.  , 5.  , 5.61])

In [194]:
data3 = ((2,5,2,6,5),(4,5,6,78,12.5),(3.5,3.,21,32,7),(7.,21,6,7,8),(6,22.,2.5,6.4,2))
arr3 = np.array(data3)
arr3

array([[ 2. ,  5. ,  2. ,  6. ,  5. ],
       [ 4. ,  5. ,  6. , 78. , 12.5],
       [ 3.5,  3. , 21. , 32. ,  7. ],
       [ 7. , 21. ,  6. ,  7. ,  8. ],
       [ 6. , 22. ,  2.5,  6.4,  2. ]])

In [195]:
arr3[[4,2,0]]

array([[ 6. , 22. ,  2.5,  6.4,  2. ],
       [ 3.5,  3. , 21. , 32. ,  7. ],
       [ 2. ,  5. ,  2. ,  6. ,  5. ]])

In [196]:
arr3[[4,3],[4,2]]


array([2., 6.])

In [197]:
arr3[:,[3,1,-1]]


array([[ 6. ,  5. ,  5. ],
       [78. ,  5. , 12.5],
       [32. ,  3. ,  7. ],
       [ 7. , 21. ,  8. ],
       [ 6.4, 22. ,  2. ]])

In [200]:
arr3[:,3].ndim

1

In [201]:
arr3[:,[3]]

array([[ 6. ],
       [78. ],
       [32. ],
       [ 7. ],
       [ 6.4]])

In [203]:
np.ix_([0, -1],[0,1,3])

(array([[ 0],
        [-1]]),
 array([[0, 1, 3]]))

In [206]:
arr3[np.ix_([0, -1],[0,1,3])]

array([[ 2. ,  5. ,  6. ],
       [ 6. , 22. ,  6.4]])

In [208]:
arr3[[0,-1]][:,[0,1,3]]

SyntaxError: unexpected EOF while parsing (<ipython-input-208-f52ec8159811>, line 1)