In [2]:
import numpy as np


In [4]:
a = np.array([1,2,3])
b =np.array([4,5,6])

In [8]:
vector = np.dot(a,b)
vector

32

In [16]:
arr1 = np.array([5,15,25,40]).reshape(4,1)
 # = np.matrix([5,15,25,40])

In [14]:
arr1

array([[ 5],
       [15],
       [25],
       [40]])

matrix([[ 5, 15, 25, 40]])

In [20]:
arr3 =np.arange(12).reshape(3,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
arr4 = np.dot(arr3,arr1)
arr4

array([[185],
       [525],
       [865]])

In [28]:
arr9 = np.array([[6,-1],[8,1]])
arr9

array([[ 6, -1],
       [ 8,  1]])

In [29]:
arr10 = np.array([[6,10],[-1,1]])
arr10

array([[ 6, 10],
       [-1,  1]])

In [32]:
np.dot(arr9,arr10)


array([[37, 59],
       [47, 81]])

In [33]:
data2 = ((8.5,6,4.1,2,0.7),(1.5,3,5.4,7,9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19),(12,3.4,1.2,4,7))


In [36]:
arr2 = np.array(data2)
arr2

array([[ 8.5,  6. ,  4.1,  2. ,  0.7],
       [ 1.5,  3. ,  5.4,  7. ,  9. ],
       [ 3.2,  4.5,  6. ,  3. ,  9. ],
       [11.2, 13.4, 15.6, 17.8, 19. ],
       [12. ,  3.4,  1.2,  4. ,  7. ]])

In [40]:
np.transpose(arr2)
arr2_inv = np.linalg.inv(arr2)
arr2_inv

array([[ 0.3711286 ,  0.64731268, -0.0944825 , -0.28783832,  0.03338093],
       [-0.99835863, -2.12854628,  0.28018759,  0.8859163 ,  0.07166708],
       [ 1.01614191,  1.83865984, -0.14218104, -0.76987825, -0.19313169],
       [-0.06423355,  0.00270201, -0.20641187,  0.09440559,  0.0120923 ],
       [-0.28879427, -0.39255638,  0.16820241,  0.141168  ,  0.07702138]])

In [44]:
np.set_printoptions(suppress=True,precision=2)
np.dot(arr2_inv,arr2)


array([[ 1., -0.,  0., -0.,  0.],
       [-0.,  1.,  0., -0., -0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  1.]])

In [45]:
np.diag(arr2)

array([ 8.5,  3. ,  6. , 17.8,  7. ])

In [47]:
A = np.array([[3,2,1],[2,3,1],[1,2,3]])
B = np.array([[38],[34],[26]])

In [50]:
X = np.linalg.solve(A,B)
X

array([[8.67],
       [4.67],
       [2.67]])

In [51]:
np.dot(A,X)

array([[38.],
       [34.],
       [26.]])