In [1]:
import numpy as np

In [8]:
np.random.random((3,4))


array([[0.22381918, 0.89933423, 0.26373624, 0.65647853],
       [0.2710812 , 0.76948464, 0.85413998, 0.46356865],
       [0.56539501, 0.96636184, 0.22139354, 0.26838635]])

In [10]:
np.random.seed(100)
np.random.random((3,4))

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212]])

In [14]:
np.random.randint(1,100,size=[10,10])

array([[94, 45, 17, 52, 55, 56, 84, 43, 62, 38],
       [81,  3, 63, 82, 17, 71, 54, 99, 97, 48],
       [49, 10, 50, 54, 35,  4, 12, 50, 30, 37],
       [94, 68, 27, 53, 37, 74, 32, 86, 93, 69],
       [84, 72, 62, 94, 37, 43, 14, 49, 83, 33],
       [39, 41, 54, 94, 15, 39, 87, 38,  1, 60],
       [42, 45, 20, 77, 67, 14, 88, 66, 69, 55],
       [ 1, 88, 84, 11, 66,  3, 88, 77, 40, 37],
       [36, 27, 20,  5, 40, 88, 75, 80, 93, 53],
       [45, 14, 34, 16, 18, 89, 24, 60,  9, 41]])

In [16]:
np.random.uniform(low=0,high=100,size=(10,10))

array([[70.45163022, 49.75106876, 10.34215554, 51.41631388, 62.76829228,
        51.74183697, 26.46944005,  8.66959882, 71.98245726, 20.39413879],
       [36.16638145, 77.7685414 , 88.1042226 , 30.27936925, 15.03827745,
        73.81609983, 91.21589889, 93.62564913,  2.064955  , 47.27383828],
       [ 4.60330415,  5.37053469, 63.77857482,  7.30084097, 99.14306336,
        77.9529841 , 69.96321564, 12.89979948, 27.16941897, 59.9993007 ],
       [61.86455345, 56.29452004, 65.27749117, 23.42567279, 31.60363579,
        74.56147409, 87.2716013 , 48.28286365, 36.80122837,  9.65436586],
       [68.81137364,  3.414638  ,  6.84865559, 90.95072819, 55.707376  ,
        29.50211823, 73.31183749, 27.08576711, 86.97817851, 66.15484508],
       [39.45512185, 15.04316123, 82.07904684, 46.20280287, 47.64667659,
        59.31493678, 76.60000484, 99.33383895, 35.52196244,  6.0532644 ],
       [25.35656371, 23.06351043, 73.36123626, 62.4465215 , 71.38727082,
        71.35272254, 17.27195374, 34.27048792

In [23]:
np.set_printoptions(precision=5)
np.random.rand(4,3)

array([[0.1334 , 0.10386, 0.65045],
       [0.62511, 0.66955, 0.9012 ],
       [0.26645, 0.65715, 0.74851],
       [0.93454, 0.89698, 0.34362]])

In [29]:
np.std(np.random.normal(1,3,size=10000))

3.0111652632565673

In [32]:
np.set_printoptions(precision=5)
np.random.randn(10)

array([-0.53268, -0.17441,  0.70529,  1.93195,  0.51882,  0.03376,
        0.18766, -0.0602 ,  1.9441 ,  1.13497])

In [34]:
sample = np.random.normal(size=(4,4))

array([[ 0.08581, -0.19587, -0.04115, -0.51932],
       [ 0.44802, -0.18532,  0.83593,  0.14025],
       [ 0.62916,  1.42602,  0.75444,  1.81683],
       [ 0.87851,  1.38765,  0.88624,  1.77119]])

In [36]:
s= np.array([1,2,5,6,7,9,10])

In [41]:
np.random.shuffle(s)
s

array([ 5,  7,  2, 10,  1,  9,  6])

In [45]:
np.random.permutation(s)

array([ 5,  2,  7, 10,  9,  1,  6])

In [44]:
s

array([ 5,  7,  2, 10,  1,  9,  6])