In [140]:
import numpy as np

In [141]:
data = ((2.3,5,2,6,5),(4.5,5,6,78,12.5),(3.5,3.,21,32,7),(7.,21,6,7,8),(6,22.,2.5,6.4,2),(9.5,10,20,67,1))
arr = np.array(data)
arr

array([[ 2.3,  5. ,  2. ,  6. ,  5. ],
       [ 4.5,  5. ,  6. , 78. , 12.5],
       [ 3.5,  3. , 21. , 32. ,  7. ],
       [ 7. , 21. ,  6. ,  7. ,  8. ],
       [ 6. , 22. ,  2.5,  6.4,  2. ],
       [ 9.5, 10. , 20. , 67. ,  1. ]])

In [142]:
arr.reshape(10,3)

array([[ 2.3,  5. ,  2. ],
       [ 6. ,  5. ,  4.5],
       [ 5. ,  6. , 78. ],
       [12.5,  3.5,  3. ],
       [21. , 32. ,  7. ],
       [ 7. , 21. ,  6. ],
       [ 7. ,  8. ,  6. ],
       [22. ,  2.5,  6.4],
       [ 2. ,  9.5, 10. ],
       [20. , 67. ,  1. ]])

In [143]:
# arr.reshape(4,10)
arr

array([[ 2.3,  5. ,  2. ,  6. ,  5. ],
       [ 4.5,  5. ,  6. , 78. , 12.5],
       [ 3.5,  3. , 21. , 32. ,  7. ],
       [ 7. , 21. ,  6. ,  7. ,  8. ],
       [ 6. , 22. ,  2.5,  6.4,  2. ],
       [ 9.5, 10. , 20. , 67. ,  1. ]])

In [144]:
arr1 = arr.resize(5,6)
arr1

In [145]:
arr


array([[ 2.3,  5. ,  2. ,  6. ,  5. ,  4.5],
       [ 5. ,  6. , 78. , 12.5,  3.5,  3. ],
       [21. , 32. ,  7. ,  7. , 21. ,  6. ],
       [ 7. ,  8. ,  6. , 22. ,  2.5,  6.4],
       [ 2. ,  9.5, 10. , 20. , 67. ,  1. ]])

In [146]:
arr.shape = [10,3]

In [147]:
arr.ravel()

array([ 2.3,  5. ,  2. ,  6. ,  5. ,  4.5,  5. ,  6. , 78. , 12.5,  3.5,
        3. , 21. , 32. ,  7. ,  7. , 21. ,  6. ,  7. ,  8. ,  6. , 22. ,
        2.5,  6.4,  2. ,  9.5, 10. , 20. , 67. ,  1. ])

In [148]:
arr


array([[ 2.3,  5. ,  2. ],
       [ 6. ,  5. ,  4.5],
       [ 5. ,  6. , 78. ],
       [12.5,  3.5,  3. ],
       [21. , 32. ,  7. ],
       [ 7. , 21. ,  6. ],
       [ 7. ,  8. ,  6. ],
       [22. ,  2.5,  6.4],
       [ 2. ,  9.5, 10. ],
       [20. , 67. ,  1. ]])

In [149]:
arr.reshape(-1)


array([ 2.3,  5. ,  2. ,  6. ,  5. ,  4.5,  5. ,  6. , 78. , 12.5,  3.5,
        3. , 21. , 32. ,  7. ,  7. , 21. ,  6. ,  7. ,  8. ,  6. , 22. ,
        2.5,  6.4,  2. ,  9.5, 10. , 20. , 67. ,  1. ])

In [150]:
arr.ravel()[2] = 100
arr

array([[  2.3,   5. , 100. ],
       [  6. ,   5. ,   4.5],
       [  5. ,   6. ,  78. ],
       [ 12.5,   3.5,   3. ],
       [ 21. ,  32. ,   7. ],
       [  7. ,  21. ,   6. ],
       [  7. ,   8. ,   6. ],
       [ 22. ,   2.5,   6.4],
       [  2. ,   9.5,  10. ],
       [ 20. ,  67. ,   1. ]])

In [151]:
arr.flatten()
arr


array([[  2.3,   5. , 100. ],
       [  6. ,   5. ,   4.5],
       [  5. ,   6. ,  78. ],
       [ 12.5,   3.5,   3. ],
       [ 21. ,  32. ,   7. ],
       [  7. ,  21. ,   6. ],
       [  7. ,   8. ,   6. ],
       [ 22. ,   2.5,   6.4],
       [  2. ,   9.5,  10. ],
       [ 20. ,  67. ,   1. ]])

In [152]:
arr2 = arr
arr2.ndim

2

In [153]:
arr2[:,np.newaxis].ndim

3

In [154]:
x = np.arange(3)
x.ndim

1

In [155]:
x[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [156]:
x[:,np.newaxis,np.newaxis]

array([[[0]],

       [[1]],

       [[2]]])

In [157]:
y = np.arange(3,6)
y

array([3, 4, 5])

In [158]:
x[:,np.newaxis] * y

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  8, 10]])

In [159]:
arr1 = np.arange(20).reshape(5,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [160]:
arr2 = arr.reshape(5,6)
arr2

array([[  2.3,   5. , 100. ,   6. ,   5. ,   4.5],
       [  5. ,   6. ,  78. ,  12.5,   3.5,   3. ],
       [ 21. ,  32. ,   7. ,   7. ,  21. ,   6. ],
       [  7. ,   8. ,   6. ,  22. ,   2.5,   6.4],
       [  2. ,   9.5,  10. ,  20. ,  67. ,   1. ]])

In [161]:
np.hstack((arr1,arr2))


array([[  0. ,   1. ,   2. ,   3. ,   2.3,   5. , 100. ,   6. ,   5. ,
          4.5],
       [  4. ,   5. ,   6. ,   7. ,   5. ,   6. ,  78. ,  12.5,   3.5,
          3. ],
       [  8. ,   9. ,  10. ,  11. ,  21. ,  32. ,   7. ,   7. ,  21. ,
          6. ],
       [ 12. ,  13. ,  14. ,  15. ,   7. ,   8. ,   6. ,  22. ,   2.5,
          6.4],
       [ 16. ,  17. ,  18. ,  19. ,   2. ,   9.5,  10. ,  20. ,  67. ,
          1. ]])

In [162]:
arr3 = np.array([[23.6,123,231,65],[1.2,23,52,12]])
arr3

array([[ 23.6, 123. , 231. ,  65. ],
       [  1.2,  23. ,  52. ,  12. ]])

In [163]:
np.vstack([arr1,arr3])


array([[  0. ,   1. ,   2. ,   3. ],
       [  4. ,   5. ,   6. ,   7. ],
       [  8. ,   9. ,  10. ,  11. ],
       [ 12. ,  13. ,  14. ,  15. ],
       [ 16. ,  17. ,  18. ,  19. ],
       [ 23.6, 123. , 231. ,  65. ],
       [  1.2,  23. ,  52. ,  12. ]])

In [164]:
np.concatenate((arr1,arr2),axis=1)


array([[  0. ,   1. ,   2. ,   3. ,   2.3,   5. , 100. ,   6. ,   5. ,
          4.5],
       [  4. ,   5. ,   6. ,   7. ,   5. ,   6. ,  78. ,  12.5,   3.5,
          3. ],
       [  8. ,   9. ,  10. ,  11. ,  21. ,  32. ,   7. ,   7. ,  21. ,
          6. ],
       [ 12. ,  13. ,  14. ,  15. ,   7. ,   8. ,   6. ,  22. ,   2.5,
          6.4],
       [ 16. ,  17. ,  18. ,  19. ,   2. ,   9.5,  10. ,  20. ,  67. ,
          1. ]])

In [165]:
arr4 = np.array([[0,1],[2,3]])
arr4

array([[0, 1],
       [2, 3]])

In [166]:
np.tile(arr4,(4,4))



array([[0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3]])

In [167]:
arr5 = np.arange(8).reshape(2,2,2)
arr5

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [168]:
arr5.ndim

3

In [169]:
arr5.shape

(2, 2, 2)

In [172]:
arr5[0][0][0]


0