In [1]:
import numpy as np

In [10]:
np.set_printoptions(precision=5)
data = np.random.random((6,7))

In [11]:
data.shape


(6, 7)

In [13]:
data.sum(axis=0)


array([3.03894, 3.30856, 3.27716, 1.7546 , 2.3537 , 3.93418, 2.6606 ])

In [15]:
data.sum(axis=1)

array([3.2197 , 2.54668, 4.68977, 3.62915, 2.52659, 3.71584])

In [17]:
data.mean(axis=0)

array([0.50649, 0.55143, 0.54619, 0.29243, 0.39228, 0.6557 , 0.44343])

In [19]:
data.mean(axis=1)

array([0.45996, 0.36381, 0.66997, 0.51845, 0.36094, 0.53083])

In [22]:
data.cumsum()

array([ 0.34832,  0.90815,  1.81017,  1.95822,  2.55374,  2.98849,
        3.2197 ,  3.59042,  3.97678,  4.48313,  4.53447,  4.67829,
        5.25921,  5.76638,  5.87879,  6.62658,  7.6042 ,  8.58735,
        8.63585,  9.58126, 10.45615, 11.34634, 11.87433, 12.09885,
       12.43924, 12.9675 , 13.93457, 14.0853 , 14.53939, 14.68721,
       15.26332, 15.29976, 15.68891, 16.45895, 16.61189, 17.4751 ,
       18.41386, 18.5044 , 18.69962, 19.34807, 19.58407, 20.32773])

In [26]:
data.cumsum(axis=1)

array([[0.34832, 0.90815, 1.81017, 1.95822, 2.55374, 2.98849, 3.2197 ],
       [0.37072, 0.75708, 1.26343, 1.31477, 1.45859, 2.03951, 2.54668],
       [0.11241, 0.86021, 1.83782, 2.82097, 2.86947, 3.81488, 4.68977],
       [0.8902 , 1.41818, 1.6427 , 1.9831 , 2.51135, 3.47842, 3.62915],
       [0.45409, 0.60191, 1.17802, 1.21446, 1.60361, 2.37365, 2.52659],
       [0.86321, 1.80197, 1.89251, 2.08773, 2.73618, 2.97218, 3.71584]])

In [28]:
data.cumprod()

array([3.48317e-01, 1.95000e-01, 1.75893e-01, 2.60419e-02, 1.55084e-02,
       6.74219e-03, 1.55888e-03, 5.77904e-04, 2.23283e-04, 1.13059e-04,
       5.80465e-06, 8.34824e-07, 4.84962e-07, 2.45958e-07, 2.76492e-08,
       2.06758e-08, 2.02130e-08, 1.98724e-08, 9.63911e-10, 9.11289e-10,
       7.97276e-10, 7.09731e-10, 3.74727e-10, 8.41346e-11, 2.86390e-11,
       1.51287e-11, 1.46305e-11, 2.20522e-12, 1.00137e-12, 1.48026e-13,
       8.52789e-14, 3.10748e-15, 1.20928e-15, 9.31196e-16, 1.42420e-16,
       1.22938e-16, 1.15409e-16, 1.04499e-17, 2.04002e-18, 1.32285e-18,
       3.12192e-19, 2.32165e-19])

In [31]:
np.percentile(data,50)

0.4802180882474685

In [33]:
np.median(data)


0.4802180882474685

In [35]:
np.percentile(data,[10,20,30,40,50,60])


array([0.11556, 0.15117, 0.23265, 0.37698, 0.48022, 0.5472 ])

In [37]:
np.ptp(data)

0.9467073532796545

In [39]:
data.max()-data.min()

0.9467073532796545

In [40]:
np.sum(data>0.3)

28