In [65]:
import numpy as np

In [66]:
a = np.array([[1,2,3],[4,5,6]])
b = a.copy()
a

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
a.fill(0)

In [68]:
a


array([[0, 0, 0],
       [0, 0, 0]])

In [69]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
import copy
