In [201]:
import numpy as np


In [202]:
arr1 = np.array([[0,1,3],[4,2,9],[4,5,8],[1,-3,4]])

In [203]:
arr1

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  8],
       [ 1, -3,  4]])

In [204]:
arr2 = np.arange(12).reshape(4,3)
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [205]:
arr1 + arr2

array([[ 0,  2,  5],
       [ 7,  6, 14],
       [10, 12, 16],
       [10,  7, 15]])

In [206]:
arr3 = np.array([1,2,3])

In [207]:
arr1 + arr3

array([[ 1,  3,  6],
       [ 5,  4, 12],
       [ 5,  7, 11],
       [ 2, -1,  7]])

In [208]:
arr4 = np.array([[1],[2],[3],[4]])
arr4

array([[1],
       [2],
       [3],
       [4]])

In [209]:
arr1

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  8],
       [ 1, -3,  4]])

In [210]:
arr1 + arr4

array([[ 1,  2,  4],
       [ 6,  4, 11],
       [ 7,  8, 11],
       [ 5,  1,  8]])

In [211]:
arr5 = np.array([1,2,3])
arr5

array([1, 2, 3])

In [212]:
arr1

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  8],
       [ 1, -3,  4]])

In [213]:
arr1 + arr5

array([[ 1,  3,  6],
       [ 5,  4, 12],
       [ 5,  7, 11],
       [ 2, -1,  7]])

In [214]:
math = np.array([98,83,86,92,67,82])

In [215]:
english = np.array([68,74,66,82,75,89])
chinese = np.array([92,83,96,76,60,93])

In [216]:
total = english+chinese+math
total

array([258, 240, 248, 250, 202, 264])

In [217]:
np.add(chinese,np.add(math,english))

array([258, 240, 248, 250, 202, 264])

In [218]:
np.subtract(math,english)

array([30,  9, 20, 10, -8, -7])

In [219]:
height = np.array([165,172,169,198,173])

In [220]:
weight = np.array([62,50,60,70,80])

In [221]:
weight/(height/100) **2

array([22.77318641, 16.90102758, 21.0076678 , 17.85532089, 26.7299275 ])

In [222]:
np.divide(weight,np.divide(height,100)**2)

array([22.77318641, 16.90102758, 21.0076678 , 17.85532089, 26.7299275 ])

In [223]:
np.power(arr2,2)

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]], dtype=int32)

In [224]:
s=np.array([1,2,3,2,5,7,7,9,2,6,7,7,3])

In [225]:
test = [2,4,7,8]

In [226]:
np.unique(s)


array([1, 2, 3, 5, 6, 7, 9])

In [227]:
np.in1d(s,test)


array([False,  True, False,  True, False,  True,  True, False,  True,
       False,  True,  True, False])

In [228]:
np.intersect1d(test,s)

array([2, 7])

In [229]:
np.union1d(s,test)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
np.setdiff1d(s,test)

array([1, 3, 5, 6, 9])

In [231]:
arr6 = np.array([[0,1,3],[4,2,1],[5,4,9],[1,-3,4]])
arr7 = np.array([1,2,3])

In [232]:
arr6 == arr7


array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [233]:
np.equal(arr6,arr7)

array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [234]:
np.greater(arr6,arr7).any()

True

In [235]:
np.greater_equal(arr6,arr7)

array([[False, False,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [236]:
np.less_equal(arr6,arr7)

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [237]:
np.logical_and(arr6,arr7)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [238]:
np.array(np.nan)


array(nan)

In [239]:
np.logical_or(arr6,arr7)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [240]:
o = np.array(False)
z = np.all([-1,4,5],out=o)

In [241]:
id(z),id(o)


(2210930813408, 2210930813408)

In [242]:
np.allclose([1e10,1e-7], [1.00001e10,1e-8])

False

In [243]:
arr8 = np.array([np.nan, 1])
arr8


array([nan,  1.])

In [244]:
np.isinf(arr8)


array([False, False])

In [252]:
arr9 = arr1

In [246]:
np.sort(arr1)

array([[ 0,  1,  3],
       [ 2,  4,  9],
       [ 4,  5,  8],
       [-3,  1,  4]])

In [256]:
arr1

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  8],
       [ 1, -3,  4]])

In [248]:
np.argsort(arr1,axis=0)

array([[0, 3, 0],
       [3, 0, 3],
       [1, 1, 2],
       [2, 2, 1]], dtype=int64)

In [254]:
arr9.argmax(axis=0)

array([1, 2, 1], dtype=int64)

In [257]:
np.where(arr1>3)

(array([1, 1, 2, 2, 2, 3], dtype=int64),
 array([0, 2, 0, 1, 2, 2], dtype=int64))

In [259]:
np.where(arr1>3, 1,0)

array([[0, 0, 0],
       [1, 0, 1],
       [1, 1, 1],
       [0, 0, 1]])

In [262]:
np.extract(arr1>3,arr1)

array([4, 9, 4, 5, 8, 4])