In [45]:
list(map(lambda x: x**2 ,[1, 2, 3, 4, 5]))

[1, 4, 9, 16, 25]

In [46]:
from functools import reduce
items = [1,2,3,4,5,6,7,8,9,10]
reduce(lambda x, y: x+ y,range(1,101))

5050

In [47]:
list(filter(lambda x: x % 2 == 0, range(21)))


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [48]:
lis = [1, 2, 3, 4, 'sada', 'qwe', '-123', 54.32, -7]
list(filter(lambda x: 1 if isinstance(x, int) else 0, lis))

[1, 2, 3, 4, -7]

In [ ]:
import numpy as np

data = ((2.3,5,2,6,5),(4.5,5,6,78,12.5),(3.5,3.,21,32,7),(7.,21,6,7,8),(6,22.,2.5,6.4,2),(9.5,10,20,67,1))
arr = np.array(data)

In [62]:
x = np.arange(3)
x.ndim

1

In [65]:
x[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [64]:
x[:,np.newaxis,np.newaxis]

array([[[0]],

       [[1]],

       [[2]]])

In [70]:
y = np.arange(3,6)
y

array([3, 4, 5])

In [69]:
x[:,np.newaxis] * y

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  8, 10]])

In [74]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
arr2 = arr.reshape(5,6)
arr2

array([[  2.3,   5. ,   2. ,   6. ,   5. ,   4.5],
       [  5. ,   6. ,  78. ,  12.5,   3.5,   3. ],
       [ 21. ,  32. ,   7. ,   7. ,  21. ,   6. ],
       [  7. , 100. ,   6. ,  22. ,   2.5,   6.4],
       [  2. ,   9.5,  10. ,  20. ,  67. ,   1. ]])